### ISSUE TITLE
apk

### ISSUE THREAD

**Issue by cristi2005** [Jnnshschl/AndroidBMSApp#1]
Hi Jannis,

Can you send my android apk file for BMS Monitor app ?

Thank you,
Cristi
pc_cristi@yahoo.com

**Comment by swiv80** [comment]
Hi Jannis, Can I also try your app. I like the look of it. 
Is it possible I could have the apk as well?

**Comment by Jnnshschl** [comment]
Uploaded an apk here: [https://github.com/Jnnshschl/AndroidBMSApp/releases/tag/1.0](https://github.com/Jnnshschl/AndroidBMSApp/releases/tag/1.0)

**Comment by swiv80** [comment]
Cheers, am i doing something wrong is says I cant install the app on my device, I have a pixel

**Comment by Jnnshschl** [comment]
Reuploaded the APK, now it should work.

**Comment by cristi2005** [comment]
Thank you Janis for sharing, work great.
